import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Hamburger, HamburgerIcon, LucideHamburger } from "lucide-react";
import NavBar from "./components/NavBar";
import BottomNav from "./components/BottomNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative bg-gray-300`}


      >
        <NavBar />

        <div className="absolute w-[400px] h-[400px] rounded-full -translate-x-2/4 left-2/5  bg-purple-600 -top-10 ">h</div>
        <div className="absolute w-[400px] h-[400px] rounded-full -translate-x-[40%] left-2/5  bg-blue-700 top-32 ">h</div>

        <div className="flex min-h-screen  items-center justify-center pb-20  min-h-[100vh] font-sans dark:bg-black bg-gray-200/30 backdrop-blur-2xl">
          {children}

        </div>
        <BottomNav />
      </body>
    </html>
  );
}
